/** Lógica movida para `@codingpro/core` (compartilhada com o Desktop) — mantido como re-export. */
export {
  blocoPlanoAtivo,
  type ClassificacaoArquiteto,
  classificarRespostaArquiteto,
  executarComandoPlan,
  formatarPerguntaUi,
  interpretarResposta,
  mensagemHistoricoPlano,
  type OpcaoPergunta,
  type PerguntaPlano,
  type PlanIo,
  type PlanoAtivo,
  parsePerguntas,
  promptFasePerguntas,
  promptFasePlano,
  type RespostaPergunta,
  type ResultadoPlan,
  salvarPlanoEmDisco,
} from "@codingpro/core";
